primes:	primes.bur
	powershell "./bur.ps1 -in primes.bur -out run.exe"
print:	print.bur
	powershell "./bur.ps1 -in print.bur -out run.exe"
fib:	fib.bur
	powershell "./bur.ps1 -in fib.bur -out run.exe"
